"""
Load a trained EFNO policy checkpoint and a precomputed numerical-adjoint result file,
then export/plot RL-vs-adjoint comparison.

Writes:
  - `comparison_summary.csv`: per-sample costs and returns
  - `policy_vs_adjoint_export.npz`: grids x, t, and trajectories/controls for RL vs numerical adjoint
  - optional `comparison_u.png`: temperature snapshots
    - optional `comparison_a.png`: control snapshots
"""
from __future__ import annotations

import argparse
import csv
import os
import sys
from pathlib import Path

import matplotlib

matplotlib.use("Agg")

import numpy as np
import torch

if __package__ in (None, ""):
    # Direct script execution: python heat_rl_efno/compare_policy_adjoint.py
    repo_root = Path(__file__).resolve().parents[1]
    if str(repo_root) not in sys.path:
        sys.path.insert(0, str(repo_root))
    from heat_rl_efno.heat_env import HeatEnv, HeatEnvConfig
    from heat_rl_efno.models import ActorEFNO
    from heat_rl_efno.rollouts import rollout_policy, total_return_to_cost
else:
    from .heat_env import HeatEnv, HeatEnvConfig
    from .models import ActorEFNO
    from .rollouts import rollout_policy, total_return_to_cost


def load_actor(ckpt_path: str, device: torch.device) -> tuple[ActorEFNO, HeatEnvConfig, dict]:
    ckpt = torch.load(ckpt_path, map_location=device, weights_only=False)
    cfg: HeatEnvConfig = ckpt["cfg"]
    args: dict = ckpt["args"]
    actor = ActorEFNO(
        cfg.nx,
        cfg.nt,
        k_max=int(args["k_max"]),
        width=int(args["width"]),
        n_layers=int(args["n_layers"]),
        a_max=float(args["a_max"]),
    ).to(device)
    actor.load_state_dict(ckpt["actor"])
    actor.eval()
    return actor, cfg, args


def _xt_mesh_for_field(x: np.ndarray, t: np.ndarray) -> tuple[np.ndarray, np.ndarray]:
    """
    Build (X, T) node grids for fields stored on (nx, nt) with x[i], t[j].

    Using `imshow(..., extent=(x0,x1,t0,t1))` maps *pixel centers* to the domain corners, which
    visually mis-aligns boundary rows with x=0 and x=L. `pcolormesh` with `shading="auto"` matches
    nodal samples to their coordinates.
    """
    X, T = np.meshgrid(x.astype(np.float64), t.astype(np.float64), indexing="ij")
    return X, T


def maybe_plot(
    out_png: str,
    x: np.ndarray,
    t: np.ndarray,
    u_rl: np.ndarray,
    u_adj: np.ndarray,
):
    import matplotlib.pyplot as plt

    # u_* shape (nx, nt): rows = x index, cols = time (matches tensors in rollout)
    X, T = _xt_mesh_for_field(x, t)
    fig, axes = plt.subplots(1, 2, figsize=(10, 4), sharey=True, constrained_layout=True)
    last_im = None
    for ax, u, title in zip(
        axes,
        [u_rl, u_adj],
        ["RL policy (closed-loop)", "Numerical adjoint open-loop"],
    ):
        last_im = ax.pcolormesh(X, T, u, shading="auto", cmap="viridis")
        ax.set_title(title)
        ax.set_xlabel("x")
    axes[0].set_ylabel("t")
    if last_im is not None:
        fig.colorbar(last_im, ax=axes, shrink=0.6, label="u")
    fig.savefig(out_png, dpi=150)
    plt.close(fig)


def maybe_plot_control(
    out_png: str,
    x: np.ndarray,
    t: np.ndarray,
    a_rl: np.ndarray,
    a_adj: np.ndarray,
):
    import matplotlib.pyplot as plt

    # a_* shape (nx, nt-1): control at each time step t_n, n=0..nt-2
    t_ctrl = t[:-1] if t.shape[0] == a_rl.shape[1] + 1 else t[: a_rl.shape[1]]
    X, Tc = _xt_mesh_for_field(x, t_ctrl)
    vmax = max(float(np.max(np.abs(a_rl))), float(np.max(np.abs(a_adj))), 1e-8)

    fig, axes = plt.subplots(1, 2, figsize=(10, 4), sharey=True, constrained_layout=True)
    last_im = None
    for ax, a, title in zip(
        axes,
        [a_rl, a_adj],
        ["RL policy control", "Numerical adjoint control"],
    ):
        last_im = ax.pcolormesh(X, Tc, a, shading="auto", cmap="coolwarm", vmin=-vmax, vmax=vmax)
        ax.set_title(title)
        ax.set_xlabel("x")
    axes[0].set_ylabel("t")
    if last_im is not None:
        fig.colorbar(last_im, ax=axes, shrink=0.6, label="a")
    fig.savefig(out_png, dpi=150)
    plt.close(fig)


def main():
    p = argparse.ArgumentParser()
    p.add_argument("--checkpoint", type=str, default="heat_rl_efno_output/checkpoint_final.pt", help="Path to checkpoint_ep*.pt or final .pt")
    p.add_argument(
        "--adjoint-file",
        type=str,
        default="heat_rl_efno_compare_output/adjoint_results.npz",
        help="Path to .npz generated by generate_heat_adjoint_results.py",
    )
    p.add_argument("--out-dir", type=str, default="heat_rl_efno_compare_output")
    p.add_argument("--cpu", action="store_true")
    p.add_argument("--plot", action="store_true")
    args_ns = p.parse_args()

    device = torch.device("cpu" if args_ns.cpu or not torch.cuda.is_available() else "cuda")

    actor, cfg, train_args = load_actor(args_ns.checkpoint, device)
    env = HeatEnv(cfg, device)
    nx, nt = cfg.nx, cfg.nt
    x_norm = (env.x / cfg.L).view(1, nx, 1)
    t_norm = (env.t / cfg.T).view(1, 1, nt)

    os.makedirs(args_ns.out_dir, exist_ok=True)

    adj_data = np.load(args_ns.adjoint_file, allow_pickle=True)
    u0_np = adj_data["u0"]
    a_adj_np = adj_data["a_adj"]
    u_adj_np = adj_data["u_adj"]
    cost_adj_np = adj_data["total_cost_numerical_adjoint"]
    adj_iters = adj_data["numerical_adjoint_iters"]
    adj_success = adj_data["numerical_adjoint_success"]
    if u0_np.shape[1] != nx or u_adj_np.shape[1] != nx or u_adj_np.shape[2] != nt:
        raise ValueError(
            "Adjoint file grid shape incompatible with checkpoint cfg: "
            f"cfg(nx={nx}, nt={nt}), got u0 {u0_np.shape}, u_adj {u_adj_np.shape}"
        )
    n_samples = int(u0_np.shape[0])
    u0 = torch.tensor(u0_np, device=device, dtype=torch.float32)
    u_rl, a_rl, ret_rl = rollout_policy(actor, env, u0, x_norm, t_norm)
    cost_rl = total_return_to_cost(ret_rl)

    cost_rl_np = cost_rl.cpu().numpy()
    ret_rl_np = ret_rl.cpu().numpy()

    csv_path = os.path.join(args_ns.out_dir, "comparison_summary.csv")
    with open(csv_path, "w", newline="") as f:
        w = csv.writer(f)
        w.writerow(["idx", "total_return_rl", "total_cost_rl", "total_cost_numerical_adjoint"])
        for i in range(n_samples):
            w.writerow([i, float(ret_rl_np[i]), float(cost_rl_np[i]), float(cost_adj_np[i])])
        w.writerow(
            [
                "mean",
                float(ret_rl_np.mean()),
                float(cost_rl_np.mean()),
                float(cost_adj_np.mean()),
            ]
        )

    x_np = env.x.cpu().numpy()
    t_np = env.t.cpu().numpy()
    np.savez(
        os.path.join(args_ns.out_dir, "policy_vs_adjoint_export.npz"),
        x=adj_data["x"] if "x" in adj_data else x_np,
        t=adj_data["t"] if "t" in adj_data else t_np,
        u0=u0.cpu().numpy(),
        u_rl=u_rl.cpu().numpy(),
        a_rl=a_rl.cpu().numpy(),
        u_adj=u_adj_np,
        a_adj=a_adj_np,
        total_return_rl=ret_rl_np,
        total_cost_rl=cost_rl_np,
        total_cost_numerical_adjoint=cost_adj_np,
        numerical_adjoint_iters=np.asarray(adj_iters, dtype=np.int32),
        numerical_adjoint_success=np.asarray(adj_success, dtype=np.int8),
        checkpoint=np.array([args_ns.checkpoint], dtype=object),
        adjoint_file=np.array([args_ns.adjoint_file], dtype=object),
    )

    torch.save(
        {
            "actor_state_dict": actor.state_dict(),
            "heat_env_config": cfg,
            "train_args": train_args,
        },
        os.path.join(args_ns.out_dir, "exported_policy_operator.pt"),
    )

    print(f"Wrote {csv_path}")
    print(f"Mean total return (RL):     {ret_rl_np.mean():.6f}")
    print(f"Mean total cost (RL):       {cost_rl_np.mean():.6f}  (= -return)")
    print(f"Mean total cost (numerical adjoint): {cost_adj_np.mean():.6f}")
    print(f"Adjoint success rate: {float(np.mean(adj_success)): .2%}")

    if args_ns.plot:
        maybe_plot(
            os.path.join(args_ns.out_dir, "comparison_u.png"),
            x_np,
            t_np,
            u_rl[0].cpu().numpy(),
            u_adj_np[0],
        )
        maybe_plot_control(
            os.path.join(args_ns.out_dir, "comparison_a.png"),
            x_np,
            t_np,
            a_rl[0].cpu().numpy(),
            a_adj_np[0],
        )
        print(f"Wrote {os.path.join(args_ns.out_dir, 'comparison_u.png')}")
        print(f"Wrote {os.path.join(args_ns.out_dir, 'comparison_a.png')}")


if __name__ == "__main__":
    main()
