"""
Plot absolute error between RL and adjoint state trajectories from
`policy_vs_adjoint_export.npz` generated by compare_policy_adjoint.py.
"""
from __future__ import annotations

import argparse
import os

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np


def main():
    p = argparse.ArgumentParser()
    p.add_argument(
        "--npz",
        type=str,
        default="heat_rl_efno_compare_output/policy_vs_adjoint_export.npz",
        help="Path to export file from compare_policy_adjoint.py",
    )
    p.add_argument(
        "--out",
        type=str,
        default="heat_rl_efno_compare_output/comparison_abs_error.png",
        help="Output png path",
    )
    p.add_argument(
        "--sample-idx",
        type=int,
        default=0,
        help="Which sample to visualize in the left panel",
    )
    args = p.parse_args()

    data = np.load(args.npz, allow_pickle=True)
    x = data["x"]  # (nx,)
    t = data["t"]  # (nt,)
    u_rl = data["u_rl"]  # (B, nx, nt)
    u_adj = data["u_adj"]  # (B, nx, nt)

    abs_err = np.abs(u_rl - u_adj)
    i = int(np.clip(args.sample_idx, 0, abs_err.shape[0] - 1))
    err_i = abs_err[i]
    err_mean = abs_err.mean(axis=0)

    extent = (float(x[0]), float(x[-1]), float(t[0]), float(t[-1]))
    vmax = float(max(err_i.max(), err_mean.max(), 1e-12))

    fig, axes = plt.subplots(1, 2, figsize=(11, 4), sharey=True, constrained_layout=True)
    im0 = axes[0].imshow(
        err_i,
        origin="lower",
        aspect="auto",
        extent=extent,
        cmap="magma",
        vmin=0.0,
        vmax=vmax,
        interpolation="nearest",
    )
    axes[0].set_title(f"|u_RL - u_adj| (sample {i})")
    axes[0].set_xlabel("x")
    axes[0].set_ylabel("t")

    im1 = axes[1].imshow(
        err_mean,
        origin="lower",
        aspect="auto",
        extent=extent,
        cmap="magma",
        vmin=0.0,
        vmax=vmax,
        interpolation="nearest",
    )
    axes[1].set_title("|u_RL - u_adj| (mean over samples)")
    axes[1].set_xlabel("x")

    fig.colorbar(im1, ax=axes, shrink=0.72, label="absolute error")

    out_dir = os.path.dirname(args.out)
    if out_dir:
        os.makedirs(out_dir, exist_ok=True)
    fig.savefig(args.out, dpi=150)
    plt.close(fig)

    print(f"Wrote {args.out}")
    print(f"Global max abs error: {abs_err.max():.6e}")
    print(f"Global mean abs error: {abs_err.mean():.6e}")


if __name__ == "__main__":
    main()
